### Day 16

### Pandas

In [1]:
#pandas--library ---used to in data cleaning, data manipulation, data preprocessing

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import pandas as pd


In [4]:
#pandas-- 2 data formats
#1 Series-- 1D column
#2 DataFrame-- 2D data (columns and rows)


In [5]:
#Series
a=[1,2,3,4,5]
print(a)
print(type(a))
n=pd.Series(a)
print(n)
print(type(n))
print(n.dtype)

[1, 2, 3, 4, 5]
<class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
int64


In [6]:
b=pd.Series([1.0,2.0,3.0,4.0,5.0])
print(b)
print(type(b))
print(b.dtype)
print(b.index)
print(b.values)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
<class 'pandas.core.series.Series'>
float64
RangeIndex(start=0, stop=5, step=1)
[1. 2. 3. 4. 5.]


In [7]:
#user defined index values
b=pd.Series([1.0,2.0,3.0,4.0,5.0],index=['a','b','c','d','e'])
print(b)
print(b.index)
print(b.values)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1. 2. 3. 4. 5.]


In [8]:
print(b.iloc[1])
print(b['c'])
print(b['b':'e'])
print(b.iloc[[0,1,4]])


2.0
3.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
a    1.0
b    2.0
e    5.0
dtype: float64


In [9]:
#creating series with the array data
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
n=pd.Series(a)
print(n)
print(type(n))
c=np.array(n)
print(c)
print(type(c))

[1 2 3 4 5]
<class 'numpy.ndarray'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#filtering of data using single and multiple conditions
x=pd.Series([34,4,5,67,3,2,45,64,56,78,23,9,54,59,98,-2])
print(x>60)
print(x[x!=56])

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
dtype: bool
0     34
1      4
2      5
3     67
4      3
5      2
6     45
7     64
9     78
10    23
11     9
12    54
13    59
14    98
15    -2
dtype: int64


In [11]:
x=pd.Series([34,4,5,67,3,2,45,64,56,78,23,9,54,59,98,-2])
print(x[x>60])

3     67
7     64
9     78
14    98
dtype: int64


In [12]:
#multiple condition
x=pd.Series([34,45,6,23,89,54,33,11,17,-2])
#and & or-
print((x>20) & (x<50))
print(x[(x>20) & (x<50)])
#print values between 10 and 40
print(x[(x>10) & (x<40)])
print(x[(x>10) | (x<40)])

0     True
1     True
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    34
1    45
3    23
6    33
dtype: int64
0    34
3    23
6    33
7    11
8    17
dtype: int64
0    34
1    45
2     6
3    23
4    89
5    54
6    33
7    11
8    17
9    -2
dtype: int64


In [13]:
#Changing the values of series
x=pd.Series([1,2,3,4,5])
print(x)
x[1]=200
print(x)
x[3:]=400,500
print(x)
x[0:3:2]=100,300
print(x)
#change 200 and 500 to 7.4 and 3.8
x[1::3]=7.4,3.8
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0      1
1    200
2      3
3      4
4      5
dtype: int64
0      1
1    200
2      3
3    400
4    500
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0    100.0
1      7.4
2    300.0
3    400.0
4      3.8
dtype: float64


C:\Users\blesi\AppData\Local\Temp\ipykernel_16552\2722471187.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '(7.4, 3.8)' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  x[1::3]=7.4,3.8


In [14]:
#data preprocessing
#checking for unique values
s=pd.Series([2,5,7,2,5,8,9,2,6,7,12])
print(s.unique())

#value counts--prints the count of unique values
print(s.value_counts())

[ 2  5  7  8  9  6 12]
2     3
5     2
7     2
8     1
9     1
6     1
12    1
Name: count, dtype: int64


In [15]:
#data cleaning--handling null values
a=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
print(a)
print(a.value_counts())
#checking null values
print(a.isnull())
print(a.isnull().sum())
print(a.isna().sum())

0      1.0
1      NaN
2      2.0
3      3.0
4      5.0
5      NaN
6      7.0
7      3.0
8      5.0
9      NaN
10    11.0
11     8.0
dtype: float64
3.0     2
5.0     2
1.0     1
2.0     1
7.0     1
11.0    1
8.0     1
Name: count, dtype: int64
0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
dtype: bool
3
3


In [16]:
#filling null values
#fillna(),bfill(),ffill(),mean(),median(),mode()
#fillna()
a=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
print(a.fillna(5))  #int,float anything is alllowed

0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64


In [17]:
#bfill---fills the null value with next value
print(a.bfill())
print(a.isnull().sum())

0      1.0
1      2.0
2      2.0
3      3.0
4      5.0
5      7.0
6      7.0
7      3.0
8      5.0
9     11.0
10    11.0
11     8.0
dtype: float64
3


In [18]:
#ffill()--fills null value with previous value
print(a.ffill())
print(a.isnull().sum())

0      1.0
1      1.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [19]:
#median()
x=a.mean()
print(x)
print(a.fillna(x))
print(a.isnull().sum())
#or----print(a.fillna(a.mean()))

5.0
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [20]:
#mode()
x=a.median()
print(x)
print(a.fillna(x))
print(a.isnull().sum())
#or----print(a.fillna(a.median()))

5.0
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [21]:
#mean()
k=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
p=k.mode()
print(p)
print(k.fillna(p[1]))
#print(a.isnull().sum())
#or----print(a.fillna(a.mode()))

0    3.0
1    5.0
dtype: float64
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64


### Day 17


In [22]:
# Create a pandas Series from the list:
# [10, 20, 30, 40, 50]
# a. Add custom index labels: ['a','b','c','d','e']
# b. Print value at index 'c'
# c. Print values from 'b' to 'd'
# d. Print only first and last values using list indexing

In [23]:
c=pd.Series([10, 20, 30, 40, 50], index=['a','b','c','d','e'])
print(c)
print(c['c'])
print(c['b':'d'])
print(c['a':'e':4])
print(c.iloc[[0,-1]])

a    10
b    20
c    30
d    40
e    50
dtype: int64
30
b    20
c    30
d    40
dtype: int64
a    10
e    50
dtype: int64
a    10
e    50
dtype: int64


In [24]:
# Create a NumPy array [5, 15, 25, 35, 45]
# a. Convert it to pandas Series
# b. Print datatype
# c. Convert Series back to NumPy array

In [25]:
import numpy as np
a=np.array([5, 15, 25, 35, 45])
n=pd.Series(a)
print(n)
print(type(n))
print(n.dtype)
c=np.array(n)
print(c)
print(type(c))

0     5
1    15
2    25
3    35
4    45
dtype: int64
<class 'pandas.core.series.Series'>
int64
[ 5 15 25 35 45]
<class 'numpy.ndarray'>


In [26]:
# Given:
# [12, 45, 67, 23, 89, 34, 10, 5]
# a. Print values greater than 30
# b. Print values between 20 and 70
# c. Print values less than 15 OR greater than 80

In [27]:
d=pd.Series([12, 45, 67, 23, 89, 34, 10, 5])
print(d[d>30])  
print(d[((d>20) & (d<70))])
print(d[((d<15) | ((d>80)))])

1    45
2    67
4    89
5    34
dtype: int64
1    45
2    67
3    23
5    34
dtype: int64
0    12
4    89
6    10
7     5
dtype: int64


In [28]:
# Given:
# [1, 2, 3, 4, 5]
# a. Change second value to 100
# b. Change last two values to 200 and 300
# c. Change index posi􀆟ons 0 and 2 to 50 and 60

In [29]:
e=pd.Series([1, 2, 3, 4, 5])
print(e)
e[1]=100
e[3:]=200,300
idx = list(e.index)
idx[0] = 50
idx[2] = 60
e.index = idx

print(e)


0    1
1    2
2    3
3    4
4    5
dtype: int64
50      1
1     100
60      3
3     200
4     300
dtype: int64


In [30]:
# Given:
# [2, 5, NaN, 7, 2, 5, NaN, 8, 2, 9]
# a. Find unique values
# b. Count frequency of each value
# c. Count number of null values
# d. Fill null values using:
#  Mean
#  Forward fill
#  Backward fill
#  Mode

In [31]:
a=pd.Series([2, 5,np.nan, 7, 2, 5, np.nan, 8, 2, 9])
print(a.unique())
print(a.value_counts())
print(a.isnull().sum())


[ 2.  5. nan  7.  8.  9.]
2.0    3
5.0    2
7.0    1
8.0    1
9.0    1
Name: count, dtype: int64
2


In [32]:
x=a.mean()
print(a.fillna(x))


0    2.0
1    5.0
2    5.0
3    7.0
4    2.0
5    5.0
6    5.0
7    8.0
8    2.0
9    9.0
dtype: float64


In [33]:
print(a.bfill())

0    2.0
1    5.0
2    7.0
3    7.0
4    2.0
5    5.0
6    8.0
7    8.0
8    2.0
9    9.0
dtype: float64


In [34]:
k=pd.Series([2, 5,np.nan, 7, 2, 5, np.nan, 8, 2, 9])
p=k.mode()
print(p)
print(k.fillna(p[0]))

0    2.0
dtype: float64
0    2.0
1    5.0
2    2.0
3    7.0
4    2.0
5    5.0
6    2.0
7    8.0
8    2.0
9    9.0
dtype: float64


In [35]:
# Dataset:
# marks = [78, 56, 89, 45, 67, 90, 34, 88, 76, 54, 92, 48, 60, 73, 85]
# a. Create a Series with index as student IDs: S1 to S15
# b. Find students scoring:
# a. Above 80
# b. Between 50 and 75
# c. Count how many students scored below 50
# d. Increase marks by 5 for students scoring below 50
# e. Replace marks above 90 with 95

In [40]:
marks = pd.Series([78, 56, 89, 45, 67, 90, 34, 88, 76, 54, 92, 48, 60, 73, 85],index=['S1','S2','S3','S4','S5','S6','S7','S8','S9','S10','S11','S12','S13','S14','S15'])
print(marks[marks>80])
print(marks[(marks>=50) & (marks<=75)])
count=(marks<50).sum()
print(count)
marks[marks < 50]+=5
marks[marks > 90]=95
print(marks)

S3     89
S6     90
S8     88
S11    92
S15    85
dtype: int64
S2     56
S5     67
S10    54
S13    60
S14    73
dtype: int64
3
S1     78
S2     56
S3     89
S4     50
S5     67
S6     90
S7     39
S8     88
S9     76
S10    54
S11    95
S12    53
S13    60
S14    73
S15    85
dtype: int64


In [37]:
# Dataset:
# temps = [32, 35, None, 40, 38, None, 36, 37, None, 39, 41, None]
# a. Convert to Series
# b. Count null values
# c. Fill nulls with:
# a. Mean
# b. Forward fill
# c. Backward fill
# d. Find days where temperature > 38
# e. Replace temperatures below 33 with 33

In [48]:
temps =pd.Series([32, 35, None, 40, 38, None, 36, 37, None, 39, 41, None])
print(temps.isnull().sum())
x=temps.mean()
print(x)
print(temps.fillna(x))
print(temps.bfill())
print(temps.ffill())
print(temps[temps>38])
temps[temps<33]=33
print(temps)

4
37.25
0     32.00
1     35.00
2     37.25
3     40.00
4     38.00
5     37.25
6     36.00
7     37.00
8     37.25
9     39.00
10    41.00
11    37.25
dtype: float64
0     32.0
1     35.0
2     40.0
3     40.0
4     38.0
5     36.0
6     36.0
7     37.0
8     39.0
9     39.0
10    41.0
11     NaN
dtype: float64
0     32.0
1     35.0
2     35.0
3     40.0
4     38.0
5     38.0
6     36.0
7     37.0
8     37.0
9     39.0
10    41.0
11    41.0
dtype: float64
3     40.0
9     39.0
10    41.0
dtype: float64
0     33.0
1     35.0
2      NaN
3     40.0
4     38.0
5      NaN
6     36.0
7     37.0
8      NaN
9     39.0
10    41.0
11     NaN
dtype: float64
