### NUMPY

In [ ]:
#numpy--numeric python
# used for working with arrays and numeric values


In [1]:
#installation
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
print("version",np.__version__)

version 2.3.5


In [4]:
#creating array using list
a=[1,2,3,4,5]
print(a)
print(type(a))
x=np.array(a)
print(x)
print(type(x))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
a=[1,2,3,4,5]
print(a*2)

x=np.array([1,2,3,4,5])
print(x*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [19]:
#Methodds of Creating arrays

#1 zeros array

print(np.zeros(10))

#1 array of ones
print(np.ones(5))

#3 using arrange function
print(np.arange(1,10))

#arange with step size
print(np.arange(1,11,2))
print(np.arange(50,19,-6))

#Evenly spaced values
print(np.linspace(1,10,4))
print(np.linspace(1,10,5)) #1+10/2 ,1+5.5/2

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[50 44 38 32 26 20]
[ 1.  4.  7. 10.]
[ 1.    3.25  5.5   7.75 10.  ]


In [25]:
#types of array---1D, 2D, 3D
#creating 1D array
a=np.array([1,2,3,4,5,6])
print("1D array: ",a)
print("Dimension: ",a.ndim)

#creating 2D array
b=np.array([[1,2],[3,4]])
print("2D array: ",b)
print("Dimension: ",b.ndim)

#creating 3D array
c=np.array([[[1,2],[3,4]],[[4,5],[7,8]]])
print("3D array: ",c)
print("Dimension: ",c.ndim)

1D array:  [1 2 3 4 5 6]
Dimension:  1
2D array:  [[1 2]
 [3 4]]
Dimension:  2
3D array:  [[[1 2]
  [3 4]]

 [[4 5]
  [7 8]]]
Dimension:  3


In [31]:
#Shape,Size , Dimension and Datatype
a1=np.array([1,2,3,4,5,6,7])
print("Shape",a1.shape) #rows,columns
print("size",a1.size) #total elements
print("Dimensions:",a1.ndim)
print("Data type of values:",a1.dtype)
print(type(a1))

Shape (7,)
size 7
Dimensions: 1
Data type of values: int64
<class 'numpy.ndarray'>


In [32]:
#Shape,Size , Dimension and Datatype
a2=np.array([[1,2],[3,4],[3,6],[8,4]])
print("Shape",a2.shape) #rows,columns
print("size",a2.size) #total elements
print("Dimensions:",a2.ndim)
print("Data type of values:",a2.dtype)
print(type(a2))

Shape (4, 2)
size 8
Dimensions: 2
Data type of values: int64
<class 'numpy.ndarray'>


In [33]:
#Shape,Size , Dimension and Datatype
a3=np.array([[[1,2],[3,4]],[[4,5],[7,8]]])
print("Shape",a3.shape) #rows,columns
print("size",a3.size) #total elements
print("Dimensions:",a3.ndim)
print("Data type of values:",a3.dtype)
print(type(a3))

Shape (2, 2, 2)
size 8
Dimensions: 3
Data type of values: int64
<class 'numpy.ndarray'>


In [36]:
#Aggreagate functions 
a=np.array([1,2,3,4,5,6,7,8])
print("minimum:",np.min(a)) #a.min()
print("maximum:",np.max(a))
print("mean:",np.mean(a))
print("Median:",np.median(a))
print("sum:",np.sum(a))
print("standard deviation:",np.std(a))

minimum: 1
maximum: 8
mean: 4.5
Median: 4.5
sum: 36
standard deviation: 2.29128784747792
