### Day 16

### Pandas

In [ ]:
#pandas--library ---used to in data cleaning, data manipulation, data preprocessing

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import pandas as pd


In [3]:
#pandas-- 2 data formats
#1 Series-- 1D column
#2 DataFrame-- 2D data (columns and rows)


In [5]:
#Series
a=[1,2,3,4,5]
print(a)
print(type(a))
n=pd.Series(a)
print(n)
print(type(n))
print(n.dtype)

[1, 2, 3, 4, 5]
<class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
int64


In [7]:
b=pd.Series([1.0,2.0,3.0,4.0,5.0])
print(b)
print(type(b))
print(b.dtype)
print(b.index)
print(b.values)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
<class 'pandas.core.series.Series'>
float64
RangeIndex(start=0, stop=5, step=1)
[1. 2. 3. 4. 5.]


In [10]:
#user defined index values
b=pd.Series([1.0,2.0,3.0,4.0,5.0],index=['a','b','c','d','e'])
print(b)
print(b.index)
print(b.values)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1. 2. 3. 4. 5.]


In [19]:
print(b.iloc[1])
print(b['c'])
print(b['b':'e'])
print(b.iloc[[0,1,4]])


2.0
3.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
a    1.0
b    2.0
e    5.0
dtype: float64


In [16]:
#creating series with the array data
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
n=pd.Series(a)
print(n)
print(type(n))
c=np.array(n)
print(c)
print(type(c))

[1 2 3 4 5]
<class 'numpy.ndarray'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [24]:
#filtering of data using single and multiple conditions
x=pd.Series([34,4,5,67,3,2,45,64,56,78,23,9,54,59,98,-2])
print(x>60)
print(x[x!=56])

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
dtype: bool
0     34
1      4
2      5
3     67
4      3
5      2
6     45
7     64
9     78
10    23
11     9
12    54
13    59
14    98
15    -2
dtype: int64


In [23]:
x=pd.Series([34,4,5,67,3,2,45,64,56,78,23,9,54,59,98,-2])
print(x[x>60])

3     67
7     64
9     78
14    98
dtype: int64


In [29]:
#multiple condition
x=pd.Series([34,45,6,23,89,54,33,11,17,-2])
#and & or-
print((x>20) & (x<50))
print(x[(x>20) & (x<50)])
#print values between 10 and 40
print(x[(x>10) & (x<40)])
print(x[(x>10) | (x<40)])

0     True
1     True
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    34
1    45
3    23
6    33
dtype: int64
0    34
3    23
6    33
7    11
8    17
dtype: int64
0    34
1    45
2     6
3    23
4    89
5    54
6    33
7    11
8    17
9    -2
dtype: int64


In [39]:
#Changing the values of series
x=pd.Series([1,2,3,4,5])
print(x)
x[1]=200
print(x)
x[3:]=400,500
print(x)
x[0:3:2]=100,300
print(x)
#change 200 and 500 to 7.4 and 3.8
x[1::3]=7.4,3.8
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0      1
1    200
2      3
3      4
4      5
dtype: int64
0      1
1    200
2      3
3    400
4    500
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0    100.0
1      7.4
2    300.0
3    400.0
4      3.8
dtype: float64


C:\Users\blesi\AppData\Local\Temp\ipykernel_7688\2722471187.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '(7.4, 3.8)' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  x[1::3]=7.4,3.8


In [41]:
#data preprocessing
#checking for unique values
s=pd.Series([2,5,7,2,5,8,9,2,6,7,12])
print(s.unique())

#value counts--prints the count of unique values
print(s.value_counts())

[ 2  5  7  8  9  6 12]
2     3
5     2
7     2
8     1
9     1
6     1
12    1
Name: count, dtype: int64


In [45]:
#data cleaning--handling null values
a=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
print(a)
print(a.value_counts())
#checking null values
print(a.isnull())
print(a.isnull().sum())
print(a.isna().sum())

0      1.0
1      NaN
2      2.0
3      3.0
4      5.0
5      NaN
6      7.0
7      3.0
8      5.0
9      NaN
10    11.0
11     8.0
dtype: float64
3.0     2
5.0     2
1.0     1
2.0     1
7.0     1
11.0    1
8.0     1
Name: count, dtype: int64
0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
dtype: bool
3
3


In [47]:
#filling null values
#fillna(),bfill(),ffill(),mean(),median(),mode()
#fillna()
a=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
print(a.fillna(5))  #int,float anything is alllowed

0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64


In [50]:
#bfill---fills the null value with next value
print(a.bfill())
print(a.isnull().sum())

0      1.0
1      2.0
2      2.0
3      3.0
4      5.0
5      7.0
6      7.0
7      3.0
8      5.0
9     11.0
10    11.0
11     8.0
dtype: float64
3


In [52]:
#ffill()--fills null value with previous value
print(a.ffill())
print(a.isnull().sum())

0      1.0
1      1.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [54]:
#median()
x=a.mean()
print(x)
print(a.fillna(x))
print(a.isnull().sum())
#or----print(a.fillna(a.mean()))

5.0
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [55]:
#mode()
x=a.median()
print(x)
print(a.fillna(x))
print(a.isnull().sum())
#or----print(a.fillna(a.median()))

5.0
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
3


In [65]:
#mean()
k=pd.Series([1,np.nan,2,3,5,np.nan,7,3,5,np.nan,11,8])
p=k.mode()
print(p)
print(k.fillna(p[1]))
#print(a.isnull().sum())
#or----print(a.fillna(a.mode()))

0    3.0
1    5.0
dtype: float64
0      1.0
1      5.0
2      2.0
3      3.0
4      5.0
5      5.0
6      7.0
7      3.0
8      5.0
9      5.0
10    11.0
11     8.0
dtype: float64
